# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kiddo Movie Guide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'Font-Awesome-Swift'
  pod 'Alamofire', '~> 4.4'
  pod 'AMSmoothAlert'
  pod 'ESTabBarController'
  pod 'CQImageDownloader'
  pod 'MRProgress'
  pod 'SwiftyJSON'

  # Pods for Kiddo Movie Guide

  target 'Kiddo Movie GuideTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Expecta'
#    pod 'KIF', :configurations => ['Debug']
  end

  target 'Kiddo Movie GuideUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Expecta'
#    pod 'KIF', :configurations => ['Debug']
  end

end
